name: cron-sync-k3s-install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */12 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          GITH_ACC: ${{ secrets.GITH_ACC }}
          GITH_PW: ${{ secrets.GITH_TOKEN }}
          TZ: 'Asia/Shanghai'
        run: |
          bash cron-sync-k3s-install.sh
